# Generated by Django 5.2.8 on 2025-12-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoints",
            fields=[
                ("endpoint_id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=200)),
                ("computer", models.CharField(max_length=200)),
                ("group_id", models.CharField(max_length=100)),
                ("system_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Alerts",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("integrity_level", models.CharField(max_length=200)),
                ("role_name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("last_signal", models.DateTimeField()),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.endpoints"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaliciousActivity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.IntegerField(
                        choices=[(0, "Normal"), (1, "EoRS"), (2, "EoTH")], default=0
                    ),
                ),
                ("event_id", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=500)),
                ("command_line", models.CharField(max_length=500)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.alerts"
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.endpoints"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="endpoints",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.maliciousactivity",
            ),
        ),
    ]
