# Generated by Django 5.2.8 on 2025-12-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alerts",
            old_name="last_signal",
            new_name="system_time",
        ),
        migrations.RenameField(
            model_name="endpoints",
            old_name="system_time",
            new_name="last_signal",
        ),
    ]
